# Generated by Django 5.0.2 on 2024-03-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_title', models.CharField(max_length=255)),
                ('salary_offered', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('fulltime', 'Full-Time'), ('parttime', 'Part-Time'), ('contract', 'Contract')], max_length=20)),
                ('benefits', models.TextField()),
                ('education', models.CharField(max_length=255)),
                ('work_location', models.CharField(max_length=255)),
            ],
        ),
    ]
